
DEBUG = 10
INFO = 20
WARN = 30
ERROR = 40
DISABLED = 50

LOGDIR = "logs"
RESULTSPATH = 'viz/results.csv'
TMPMODELDIR = "zoo/tmp"
MODELDIR = "zoo"

NUM_ACTIONS_MARQUISE = 548
NUM_ACTIONS_EYRIE = 492
NUM_ACTIONS_ALLIANCE = 530
NUM_ACTIONS_VAGABOND = 604

ACTION_SPACE_SIZES = (NUM_ACTIONS_MARQUISE,NUM_ACTIONS_EYRIE,NUM_ACTIONS_ALLIANCE,NUM_ACTIONS_VAGABOND)

NUM_OBS_MARQUISE = 1538
NUM_OBS_EYRIE = 1522
NUM_OBS_ALLIANCE = 1571
NUM_OBS_VAGABOND = 1547